name: Ubuntu C/C++ CI

on:
  push:
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 0' # runs at 00:00 on every Sunday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out source code
      uses: actions/checkout@v3

    - name: Initialize and update submodules
      run: |
        make check_submodule

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake ninja-build g++ googletest libgtest-dev llvm clang

    - name: Set environment
      run: |
        echo "C_COMPILER=/usr/bin/clang" >> $GITHUB_ENV
        echo "CXX_COMPILER=/usr/bin/clang++" >> $GITHUB_ENV

    - name: Build the project
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_STANDARD=20 -G Ninja ..
        ninja -j $(nproc)

    - name: Test
      run: ./build/MeshCartography_test
